In [2]:
# Импорт необходимых библиотек
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
import os


In [3]:
# Путь к обученной модели и данным
model_path = '/content/trained_model.h5'  # Путь к обученной модели
data_dir = '/content/'                  # Путь к данным

In [5]:
# Загрузка обученной модели
model = tf.keras.models.load_model(model_path)

# Загрузка тестовых данных
X_test = pd.read_csv(os.path.join(data_dir, 'X_test.csv')).values
y_test = pd.read_csv(os.path.join(data_dir, 'y_test.csv')).values.ravel()

# Выполнение инференса на тестовых данных
y_pred_proba = model.predict(X_test)  # Получаем вероятности для классов
y_pred = np.argmax(y_pred_proba, axis=1)  # Берем индекс класса с максимальной вероятностью

# Оценка модели: вывод метрик классификации
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Setosa', 'Versicolor', 'Virginica']))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 296ms/step
Classification Report:
              precision    recall  f1-score   support

      Setosa       1.00      0.20      0.33        10
  Versicolor       0.00      0.00      0.00         9
   Virginica       0.39      1.00      0.56        11

    accuracy                           0.43        30
   macro avg       0.46      0.40      0.30        30
weighted avg       0.48      0.43      0.32        30


Confusion Matrix:
[[ 2  0  8]
 [ 0  0  9]
 [ 0  0 11]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
