In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix
import os

In [ ]:
#Путь к обученной модели и данным
model_path = '/content/trained_model.h5'
data_dir = '/content'

#Загрузка обученной модели
model = tf.keras.models.load_model(model_path)

X_test = pd.read_csv(os.path.join(data_dir, 'X_test.csv')).values
y_test = pd.read_csv(os.path.join(data_dir, 'y_test.csv')).values.ravel()

#Выполнение инференса на тестовых данных
y_pred = (model.predict(X_test) > 0.5).astype("int32")

#Оценка модели: вывод метрик классификации
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Class 0', 'Class 1', 'Class 2', 'Class 3']))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Classification Report:
              precision    recall  f1-score   support

     Class 0       0.02      1.00      0.04         1
     Class 1       0.00      0.00      0.00        10
     Class 2       0.00      0.00      0.00        34
     Class 3       0.00      0.00      0.00        10

    accuracy                           0.02        55
   macro avg       0.00      0.25      0.01        55
weighted avg       0.00      0.02      0.00        55


Confusion Matrix:
[[ 1  0  0  0]
 [10  0  0  0]
 [34  0  0  0]
 [10  0  0  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
