In [2]:
import numpy as np
import pandas as pd
from keras.models import load_model
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
# Пути к сохранённой модели и данным
model_path = 'C:/Users/Dekart/Desktop/Универ/6233 - первый сезон/6. Инженерия данных/Labs/Prerequisites/airflow/data/new_mnist_trained_model.keras'  # Укажите путь к сохранённой модели

# Загрузка обученной модели
model = load_model(model_path)

# Загрузка тестовых данных
X_test = pd.read_csv("C:/Users/Dekart/Desktop/Универ/6233 - первый сезон/6. Инженерия данных/Labs/Prerequisites/airflow/data/X_test.csv").to_numpy().astype('float32')
y_test = pd.read_csv("C:/Users/Dekart/Desktop/Универ/6233 - первый сезон/6. Инженерия данных/Labs/Prerequisites/airflow/data/y_test.csv").to_numpy().astype('int')

# Преобразование X_test в формат, необходимый модели (добавляем канал)
X_test = X_test.reshape(-1, 28, 28, 1)

# Выполнение инференса на тестовых данных
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)  # Преобразование вероятностей в классы
y_test_classes = np.argmax(y_test, axis=1)  # Преобразование one-hot в классы

# Оценка модели: вывод метрик классификации
print("Classification Report:")
print(classification_report(y_test_classes, y_pred_classes, target_names=[f"Class {i}" for i in range(10)]))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_classes, y_pred_classes))

13/13 [==============================] - 0s 10ms/step
Classification Report:
              precision    recall  f1-score   support

     Class 0       1.00      1.00      1.00        33
     Class 1       1.00      1.00      1.00        57
     Class 2       0.98      0.98      0.98        44
     Class 3       0.97      0.97      0.97        35
     Class 4       0.98      0.96      0.97        46
     Class 5       1.00      1.00      1.00        42
     Class 6       0.94      1.00      0.97        34
     Class 7       0.95      0.95      0.95        41
     Class 8       0.96      0.96      0.96        27
     Class 9       0.97      0.95      0.96        41

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       400
weighted avg       0.98      0.98      0.98       400


Confusion Matrix:
[[33  0  0  0  0  0  0  0  0  0]
 [ 0 57  0  0  0  0  0  0  0  0]
 [ 0  0 43  0  0  0  0  1  0  0]
 [ 0  0  0 34  0  0  0  0  1  0]
 [ 0  0  0  0